checking for PMD code quality

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -1,4 +1,4 @@
-name: CI/CD Pipeline for Salesforce with SonarCloud
+name: CI/CD Pipeline for Salesforce with PMD and Code Coverage
 
 on:
   push:
@@ -6,7 +6,7 @@ on:
       - 'WI-*'
 
 jobs:
-  sonarqube:
+  analyze:
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -17,6 +17,12 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
+
+      - name: Set up Java
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '11'
 
       - name: Install Node.js
         uses: actions/setup-node@v2
@@ -41,10 +47,8 @@ jobs:
         id: generate_package
         run: |
           mkdir -p ./manifest
-          git diff --name-only HEAD^..HEAD > all-changed-components.txt
-          cat all-changed-components.txt
+          git diff --name-only origin/main..HEAD > all-changed-components.txt
           grep "\.cls$" all-changed-components.txt | sed 's|force-app/main/default/classes/||' > changed-components.txt
-          cat changed-components.txt
           if [ -s changed-components.txt ]; then
             echo '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' > ./manifest/package.xml
             echo '<Package xmlns="http://soap.sforce.com/2006/04/metadata">' >> ./manifest/package.xml
@@ -68,99 +72,50 @@ jobs:
         run: echo "No Apex classes changed. Skipping deployment and tests."
         continue-on-error: true
 
-      - name: Install xmlstarlet
-        run: sudo apt-get install -y xmlstarlet
-
-      - name: Validate Deployment using Manifest
+      - name: Download PMD
         if: steps.generate_package.outputs.changed == 'true'
-        id: validate_deployment
         run: |
-          sfdx force:source:deploy --checkonly --manifest ./manifest/package.xml --target-org developer --testlevel RunSpecifiedTests --runtests TemperatureConverterTest --json > validation_result.json
+          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.41.0/pmd-bin-6.41.0.zip
+          unzip pmd-bin-6.41.0.zip
 
-      - name: Print Validation Result JSON
-        if: steps.validate_deployment.outcome == 'success'
+      - name: Run PMD Analysis
+        if: steps.generate_package.outputs.changed == 'true'
         run: |
-          echo "Printing validation_result.json for debugging:"
-          cat validation_result.json
+          ./pmd-bin-6.41.0/bin/run.sh pmd -d ./force-app/main/default/classes -R pmd-rules/apex-ruleset.xml -f text -r pmd-report.txt
+          cat pmd-report.txt
+
+      - name: Check PMD Results
+        if: steps.generate_package.outputs.changed == 'true'
+        run: |
+          if grep -q "Priority:" pmd-report.txt; then
+            echo "PMD found issues in the code. Failing the build."
+            exit 1
+          else
+            echo "No PMD issues found. Proceeding with the build."
+          fi
 
       - name: Create test-results Directory
+        if: steps.generate_package.outputs.changed == 'true'
         run: mkdir -p test-results
 
-      - name: Convert Coverage Report to XML using jq
-        if: steps.validate_deployment.outcome == 'success'
+      - name: Run Apex Tests and Generate Coverage Report
+        if: steps.generate_package.outputs.changed == 'true'
         run: |
-          cat validation_result.json | jq -r '
-          .result.details.runTestResult.codeCoverage[] | 
-          {
-            file: ("force-app/main/default/classes/" + .name + ".cls"),
-            coverage: {
-              numCoveredLines: (.numLocations - .numLocationsNotCovered),
-              numLines: .numLocations
-            }
-          }' | jq -s '{coverage: .}' > test-results/apex-codecoverage.json
+          sfdx force:apex:test:run --targetusername developer --suitenames $(cat changed-components.txt | tr '\n' ',' | sed 's/,$//') --resultformat json --outputdir test-results --codecoverage --wait 10
+          cat test-results/test-result-codecoverage.json
 
-          cat test-results/apex-codecoverage.json
-
-      - name: Convert JSON to XML using jq
+      - name: Calculate and Check Coverage
+        if: steps.generate_package.outputs.changed == 'true'
         run: |
-          echo "<coverage>" > test-results/apex-codecoverage.xml
-          cat test-results/apex-codecoverage.json | jq -r '
-          .coverage[] | 
-          "<file name=\"" + .file + "\">\n<coverage>\n<numCoveredLines>" + (.coverage.numCoveredLines|tostring) + "</numCoveredLines>\n<numLines>" + (.coverage.numLines|tostring) + "</numLines>\n</coverage>\n</file>"' >> test-results/apex-codecoverage.xml
-          echo "</coverage>" >> test-results/apex-codecoverage.xml
-
-      - name: Print Apex Code Coverage XML
-        run: |
-          echo "Printing apex-codecoverage.xml for debugging:"
-          cat test-results/apex-codecoverage.xml
-
-      - name: Calculate and Print Coverage Percentage
-        run: |
-          totalCoveredLines=$(jq '[.coverage[].coverage.numCoveredLines] | add' test-results/apex-codecoverage.json)
-          totalLines=$(jq '[.coverage[].coverage.numLines] | add' test-results/apex-codecoverage.json)
+          totalCoveredLines=$(jq '[.result.coverage.coveredLines] | add' test-results/test-result-codecoverage.json)
+          totalLines=$(jq '[.result.coverage.totalLines] | add' test-results/test-result-codecoverage.json)
           coveragePercentage=$(echo "scale=2; ($totalCoveredLines / $totalLines) * 100" | bc)
           echo "Total Covered Lines: $totalCoveredLines"
           echo "Total Lines: $totalLines"
           echo "Coverage Percentage: $coveragePercentage%"
-          echo "::set-output name=coverage_percentage::$coveragePercentage"
-
-      - name: Deploy Source to Developer Org
-        if: steps.generate_package.outputs.changed == 'true'
-        id: deploy_source
-        run: |
-          sfdx force:source:deploy --manifest ./manifest/package.xml --target-org developer --testlevel RunSpecifiedTests --runtests TemperatureConverterTest
-
-      - name: SonarQube Scan
-        uses: sonarsource/sonarqube-scan-action@v2.1.0
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-          SONAR_SCANNER_OPTS: '-Xmx1024m'
-          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
-        with:
-          args: >
-            -Dsonar.projectKey=SNHS1998_SonarQube-DevOpsCenter-Public
-            -Dsonar.apex.coverage.reportPaths=test-results/apex-codecoverage.xml
-
-      - name: Check SonarQube Quality Gate
-        id: quality_gate
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-        run: |
-          status=$(curl -s "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=SNHS1998_SonarQube-DevOpsCenter-Public" -u "${SONAR_TOKEN}:")
-          coverage=$(echo "$status" | jq -r '.projectStatus.conditions[] | select(.metricKey == "new_coverage") | .actualValue')
-          echo "Current New Code Coverage: $coverage%"
-          if (( $(echo "$coverage == null" | bc -l) )); then
-            echo "New code coverage information is not available."
-            exit 1
-          elif (( $(echo "$coverage < 80" | bc -l) )); then
-            echo "New code coverage is less than 80%. Failing the build."
+          if (( $(echo "$coveragePercentage < 80" | bc -l) )); then
+            echo "Code coverage is less than 80%. Failing the build."
             exit 1
           else
-            echo "New code coverage is sufficient. Proceeding with the build."
+            echo "Code coverage is sufficient. Proceeding with the build."
           fi
-
-      - name: Fail build on Quality Gate status
-        if: steps.quality_gate.outcome != 'success'
-        run: exit 1
